# Generated by Django 5.2.7 on 2025-11-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(null=True)),
                ('original_price', models.IntegerField(default=0)),
                ('service_price', models.IntegerField(default=0)),
                ('optom_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('change_price', models.IntegerField(default=0)),
                ('all_price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.food')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('change_price', models.IntegerField(default=0)),
                ('all_price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('orginal', 'Orginal'), ('service', 'Service'), ('optom', 'Optom')], default='orginal', max_length=20)),
                ('order', models.CharField(choices=[('input', 'input'), ('output', 'output')], default='input', max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='DebtHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('all_price', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('orginal', 'Orginal'), ('service', 'Service'), ('optom', 'Optom')], default='orginal', max_length=20)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.user')),
            ],
        ),
    ]
