# Generated by Django 5.2.7 on 2025-11-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='history',
            name='product',
        ),
        migrations.AddField(
            model_name='debthistory',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='debthistory',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='order',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
