# Generated by Django 5.2.7 on 2026-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_returnedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedproduct',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
